### ISSUE TITLE
Map in Graduation June for 322

### ISSUE THREAD

**Issue by poberwong** [Bob1993/TodoList#6]
- [x] 拍毕业照
- [x] LOL开黑
- [x] 聚餐
- [ ] K歌
- [ ] 旅游where？
  - [ ] 北方(哈尔滨、吉林、北京)？
  - [ ] 南方(济南、杭州)？
  - [ ] 国外(想想就行了)

**Comment by symsouler** [comment]
pochu

**Comment by symsouler** [comment]
K歌

**Comment by poberwong** [comment]
**Graduated...**
